### ISSUE TITLE
Missing `underscore` dependency in `package.json`

### ISSUE THREAD

**Issue by vasiliy0s** [linsir/markdown-it-task-checkbox#4]
There are especially case of missing `underscore` in package dependencies for `lodash` capability or not? If it is, there is no issue because I use `lodash` and [maked alias](https://github.com/lodash/lodash/wiki/Migrating#backbone) and dependency misssing is helpful for me.

**Comment by linsir** [comment]
I found it just now, and it fixed.thx

**Comment by arve0** [comment]
This is still missing, you've put underscore in `devDependencies`. Should be in `dependencies` when used in library. Frankly, you should **not** use `_.extend` in a library, use [`Object.assign`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) which is available in public API.

https://github.com/linsir/markdown-it-task-checkbox/blob/master/index.js#L18
