### ISSUE TITLE
Will not render correctly if spaces in "[ ] " are non-breaking spaces

### ISSUE THREAD

**Issue by NorwegianKiwi** [linsir/markdown-it-task-checkbox#8]
If either the space between [ and ], or the space after ] is a non-breaking space (ascii code 160), then it will not render the check-list correctly.

The reason for this issue, is that we have many people making content in markdown for our project, and some of them (probably using a Mac) inadvertently inserted non-breaking spaces (alt+space), and thus ended up with strange lists. 

If the owner (@linsir) agrees that non-breaking spaces should be allowed, I can make a PR that allows for non-breaking spaces. If not, please just close this issue.

**Comment by linsir** [comment]
Welcome to make a PR!

**Comment by linsir** [comment]
non-breaking spaces problem?

**Comment by NorwegianKiwi** [comment]
Yes, my apologies, I will try to make it soon, but have been quite busy lately. Thanks for reminding me!
